
/**
* ServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Service.idl
* Thursday, May 22, 2014 3:57:23 PM WIT
*/


// A very simple interface to explain this example
public interface ServiceOperations 
{
  String ping (String Message);
} // interface ServiceOperations
